// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.2
// source: contrived.proto

package trash_bin

import (
	"context"
	"reflect"
	"sync"

	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ContrivedMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ContrivedMessageRequest) Reset() {
	*x = ContrivedMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contrived_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContrivedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContrivedMessageRequest) ProtoMessage() {}

func (x *ContrivedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contrived_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContrivedMessageRequest.ProtoReflect.Descriptor instead.
func (*ContrivedMessageRequest) Descriptor() ([]byte, []int) {
	return file_contrived_proto_rawDescGZIP(), []int{0}
}

func (x *ContrivedMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ContrivedMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ContrivedMessageResponse) Reset() {
	*x = ContrivedMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contrived_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContrivedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContrivedMessageResponse) ProtoMessage() {}

func (x *ContrivedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contrived_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContrivedMessageResponse.ProtoReflect.Descriptor instead.
func (*ContrivedMessageResponse) Descriptor() ([]byte, []int) {
	return file_contrived_proto_rawDescGZIP(), []int{1}
}

func (x *ContrivedMessageResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_contrived_proto protoreflect.FileDescriptor

var file_contrived_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x76, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2d, 0x0a, 0x17, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x2e, 0x0a, 0x18, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0x6c, 0x0a, 0x10, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x69, 0x76, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a,
	0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x69, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contrived_proto_rawDescOnce sync.Once
	file_contrived_proto_rawDescData = file_contrived_proto_rawDesc
)

func file_contrived_proto_rawDescGZIP() []byte {
	file_contrived_proto_rawDescOnce.Do(func() {
		file_contrived_proto_rawDescData = protoimpl.X.CompressGZIP(file_contrived_proto_rawDescData)
	})
	return file_contrived_proto_rawDescData
}

var file_contrived_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contrived_proto_goTypes = []interface{}{
	(*ContrivedMessageRequest)(nil),  // 0: service.ContrivedMessageRequest
	(*ContrivedMessageResponse)(nil), // 1: service.ContrivedMessageResponse
}
var file_contrived_proto_depIdxs = []int32{
	0, // 0: service.ContrivedService.ContrivedMethod:input_type -> service.ContrivedMessageRequest
	1, // 1: service.ContrivedService.ContrivedMethod:output_type -> service.ContrivedMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contrived_proto_init() }
func file_contrived_proto_init() {
	if File_contrived_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contrived_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContrivedMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contrived_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContrivedMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contrived_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contrived_proto_goTypes,
		DependencyIndexes: file_contrived_proto_depIdxs,
		MessageInfos:      file_contrived_proto_msgTypes,
	}.Build()
	File_contrived_proto = out.File
	file_contrived_proto_rawDesc = nil
	file_contrived_proto_goTypes = nil
	file_contrived_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ContrivedServiceClient is the client API for ContrivedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContrivedServiceClient interface {
	ContrivedMethod(ctx context.Context, in *ContrivedMessageRequest, opts ...grpc.CallOption) (*ContrivedMessageResponse, error)
}

type contrivedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContrivedServiceClient(cc grpc.ClientConnInterface) ContrivedServiceClient {
	return &contrivedServiceClient{cc}
}

func (c *contrivedServiceClient) ContrivedMethod(ctx context.Context, in *ContrivedMessageRequest, opts ...grpc.CallOption) (*ContrivedMessageResponse, error) {
	out := new(ContrivedMessageResponse)
	err := c.cc.Invoke(ctx, "/service.ContrivedService/ContrivedMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContrivedServiceServer is the server API for ContrivedService service.
type ContrivedServiceServer interface {
	ContrivedMethod(context.Context, *ContrivedMessageRequest) (*ContrivedMessageResponse, error)
}

// UnimplementedContrivedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContrivedServiceServer struct {
}

func (*UnimplementedContrivedServiceServer) ContrivedMethod(context.Context, *ContrivedMessageRequest) (*ContrivedMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContrivedMethod not implemented")
}

func RegisterContrivedServiceServer(s *grpc.Server, srv ContrivedServiceServer) {
	s.RegisterService(&_ContrivedService_serviceDesc, srv)
}

func _ContrivedService_ContrivedMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContrivedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContrivedServiceServer).ContrivedMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ContrivedService/ContrivedMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContrivedServiceServer).ContrivedMethod(ctx, req.(*ContrivedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContrivedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.ContrivedService",
	HandlerType: (*ContrivedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContrivedMethod",
			Handler:    _ContrivedService_ContrivedMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contrived.proto",
}
